
### Create a new User
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name":"Bruno Smith",
    "email":"brunonobrega@hotmail.com",
    "password": "1234567",
    "role": "NORMAL"
}

### Login User
GET http://localhost:3000/login
Content-Type: application/json

{    
    "email":"byronnobrega@hotmail.com",
    "password": "1234567"   
}

###  Return All Users
GET http://localhost:3000/user/all
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlN2QwYWExLWE3ZGUtNDRlYi04ODM5LWRhYjgyMTc4YWU2MCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwNTgyMiwiZXhwIjoxNjc5MDA3NjIyfQ.cwooYGY-Rg-OAXnm1QSZbnAR0lRdmLIXey944po_Z4c

### Create band
POST http://localhost:3000/band/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlN2QwYWExLWE3ZGUtNDRlYi04ODM5LWRhYjgyMTc4YWU2MCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwMzYwMiwiZXhwIjoxNjc5MDA1NDAyfQ.UVaCB2hNcVHdDFnWWP5E7RgPqj3nIAzh_v2Ir8qYQ0U

{    
    "name":"O Rappa",
    "musicGenre":"rock",
    "responsible": "Marcelo Falcão"
}

### Return All Bands
GET http://localhost:3000/band/all
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlN2QwYWExLWE3ZGUtNDRlYi04ODM5LWRhYjgyMTc4YWU2MCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwMzYwMiwiZXhwIjoxNjc5MDA1NDAyfQ.UVaCB2hNcVHdDFnWWP5E7RgPqj3nIAzh_v2Ir8qYQ0U

### Return Band
GET http://localhost:3000/band/48e1c050-5cd3-478a-bc75-d1b681f2c91a
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlN2QwYWExLWE3ZGUtNDRlYi04ODM5LWRhYjgyMTc4YWU2MCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3OTAwMzYwMiwiZXhwIjoxNjc5MDA1NDAyfQ.UVaCB2hNcVHdDFnWWP5E7RgPqj3nIAzh_v2Ir8qYQ0U

